### ISSUE TITLE
Upgrade to diagram-js@4

### ISSUE THREAD

**Issue by nikku** [bpmn-io/cmmn-js#113]
Investigate if we can upgrade to diagram-js@4 to inherit some of the features shipped with the latest release.

* [ ] Checkout and test current `cmmn-js` with diagram-js upgrade
* [ ] Bump to diagram-js@4

Things we have to fix after upgrade

* [ ] Connection Preview
* [ ] Center to Center snapping on `connection.create`

**Comment by pinussilvestrus** [comment]
After doing a dry test-run with latest `diagram-js@4.0.0-beta.9` the errors [described in this comment](https://github.com/bpmn-io/diagram-js/pull/375#issuecomment-505843141) are still there

```error
1) should snap horizontally on move
     features/snapping - CmmnSnapping Siblings task to sibling
     AssertionError: expected 587 to equal 593
    at /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/spec/features/snapping/CmmnSnappingSpec.js:513:30 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:71295:31
    at Modeler.invoke (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/node_modules/didi/dist/index.js:196:19 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:36210:20)
    at Context.<anonymous> (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/helper/index.js:191:12 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:44298:13)

2) should snap vertically on move
     features/snapping - CmmnSnapping Siblings task to sibling
     AssertionError: expected 304 to equal 311
    at /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/spec/features/snapping/CmmnSnappingSpec.js:531:30 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:71311:31
    at Modeler.invoke (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/node_modules/didi/dist/index.js:196:19 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:36210:20)
    at Context.<anonymous> (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/helper/index.js:191:12 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:44298:13)

3) should snap horizontally on create
     features/snapping - CmmnSnapping Siblings task to sibling
     AssertionError: expected 598 to equal 593
    at /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/spec/features/snapping/CmmnSnappingSpec.js:549:31 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:71327:32
    at Modeler.invoke (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/node_modules/didi/dist/index.js:196:19 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:36210:20)
    at Context.<anonymous> (/var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/test/helper/index.js:191:12 <- /var/folders/8l/0qr9dffn0qs8rsnk8ls5m7rr0000gn/T/d085e8c171ac9104b7e29ee527e8c8ec.browserify.js:44298:13)
```

**Comment by pinussilvestrus** [comment]
Also seems like snapping is gone completely 

**Before** `diagram-js@3.3.1`

![before_diagram-js@3 3 1](https://user-images.githubusercontent.com/9433996/60516351-da8eae00-9cdd-11e9-89b9-c2af872fb515.gif)
**After** `diagram-js@4.0.0-beta.9`

![after_diagram-js@4 0 0-beta9](https://user-images.githubusercontent.com/9433996/60516350-da8eae00-9cdd-11e9-8432-44c2ca207a4c.gif)

**Comment by pinussilvestrus** [comment]
@barmac Can you double-check this and also check whether there is a possible breaking change we didn't were aware of?

**Comment by barmac** [comment]
Sure. Regarding TRBL snapping, it was removed in https://github.com/bpmn-io/diagram-js/commit/171057fd7752cc9ca37230c9b51f7877d40db3a0.

**Comment by barmac** [comment]
It seems that cmmn-js also implements its own bendpoints logic which blocks connection preview. Not sure if this is a breaking change too.

**Comment by barmac** [comment]
Connection preview needs to be added. I started to work on this on https://github.com/bpmn-io/cmmn-js/pull/114 and it seems that there's still some work to be done.

**Comment by barmac** [comment]
@pinussilvestrus I'm leaving this for you as you asked. I'll add some comments with my findings in #114

**Comment by pinussilvestrus** [comment]
We concluded that we will only fix the `ConnectionPreview` errors with the next release and (if it isn't to much additional work) a center-to-center connection snapping.
